---
- name: Add required permissions to data and docker_apps directories
  ansible.builtin.file:
    path: "{{ storage_dir }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
