---
- name: Create dockge container
  community.docker.docker_container:
    name: dockge
    image: louislam/dockge:1
    pull: true
    state: started
    env:
      "DOCKGE_STACKS_DIR": "/opt/stacks"
    ports:
      - "5001:5001/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ storage_dir }}/appdata/dockge/data:/app/data"
      - "{{ storage_dir }}/appdata/dockge/stacks:/opt/stacks"
    restart_policy: unless-stopped
    networks:
      - name: homelab

- name: Copy dockge compose file from template
  ansible.builtin.template:
    src: dockge_compose.j2
    dest: "{{ storage_dir }}/appdata/dockge/compose.yaml"
