---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full

- name: Check if reboot required on Ubuntu
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required on Ubuntu
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
    
- name: Check if the EXTERNALLY-MANAGED file exists
  ansible.builtin.stat:
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED
  register: file_stat

- name: Rename the file to EXTERNALLY-MANAGED-BACKUP if it exists
  ansible.builtin.copy:
    src: /usr/lib/python3.11/EXTERNALLY-MANAGED
    dest: /usr/lib/python3.11/EXTERNALLY-MANAGED-BACKUP
    remote_src: yes
  when: file_stat.stat.exists

- name: Remove EXTERNALLY-MANAGED if it exists
  ansible.builtin.file:
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED
    state: absent
  when: file_stat.stat.exists

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present

- name: Suppress login messages
  ansible.builtin.file:
    name: /home/{{ username }}/.hushlogin
    mode: "0644"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
