---
- name: Copy Samba config
  ansible.builtin.template:
    src: samba.conf.j2
    dest: /etc/samba/smb.conf

- name: Strart Samba sevice and autostart
  ansible.builtin.systemd:
    name: smbd
    state: started
    enabled: yes

- name: Creat Samba user
  ansible.builtin.user:
    name: "{{ samba_user }}"
    createhome: no
    shell: /bin/false
    state: present

- name: Set Samba password
  ansible.builtin.command: smbpasswd -s -a {{ samba_user }}
  args:
    stdin: "{{ samba_pass }}\n{{ samba_pass }}"

- name: 重启Samba服务以应用配置更改
  ansible.builtin.systemd:
    name: smbd
    state: restarted