---
- name: Copy Samba config
  ansible.builtin.template:
    src: samba.conf.j2
    dest: /etc/samba/smb.conf

- name: Strart Samba sevice and autostart
  ansible.builtin.systemd:
    name: smbd
    state: started
    enabled: yes

- name: Creat Samba user
  ansible.builtin.user:
    name: "{{ username }}"
    createhome: no
    shell: /bin/false
    state: present

- name: Set Samba password
  ansible.builtin.command: smbpasswd -s -a {{ username }}
  args:
    stdin: "{{ password }}\n{{ password }}"

- name: Restart Samba service
  ansible.builtin.systemd:
    name: smbd
    state: restarted