---
username: "<username>"

dockge_dir: /mnt/storage/appdata/dockge
storage_dir: /mnt/storage

ip_address: "<server_ip>"

samba_user: "<samba_user>"
samba_pass: "<samba_pass>"

packages:
  - unzip
  - wget
  - curl
  - git
  - python3
  - python3-pip
  - samba
  - mergerfs

pip_packages:
  - ansible
  - github3.py
  - docker

docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

mount_disks:
  - src: "LABEL=wd16t1"
    path: "/mnt/disk1"
  - src: "LABEL=wd16t2"
    path: "/mnt/disk2"
