---
username: "<username>"

dockge_dir: /mnt/storage/appdata/dockge
data_dir: /mnt/storage

puid: "<puid>"

pgid: "<pgid>"

ip_address: "<server_ip>"

timezone: "<timezone>"

samba_user: "<samba_user>"
samba_pass: "<samba_pass>"

packages:
  - unzip
  - wget
  - curl
  - git
  - python3
  - python3-pip
  - samba

pip_packages:
  - ansible
  - github3.py
  - docker

docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

mount_disks:
  - src: "LABEL=black"
    path: "/mnt/disk1"
  - src: "LABEL=nvme_old"
    path: "/mnt/disk2"
  - src: "LABEL=t5"
    path: "/mnt/disk3"

  - src: "LABEL=book"
    path: "/mnt/media"
  - src: "LABEL=other"
    path: "/mnt/others"
  - src: "LABEL=4tb"
    path: "/mnt/backup"