---
username: "<username>"
password: "<password>"
ip_address: "<server_ip>"
storage_dir: /mnt/storage

packages:
  - unzip
  - wget
  - curl
  - git
  - python3
  - python3-pip
  - samba
  - mergerfs

pip_packages:
  - ansible
  - github3.py
  - docker

docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

mount_disks:
  - src: "LABEL=px256"
    path: "/mnt/disk1"
  - src: "LABEL=wd16t2"
    path: "/mnt/disk2"
